### ISSUE TITLE
解决 Travis CI 总是更新旧博客的问题

### ISSUE THREAD

**Issue by jerryc127** [wafer-li/wafer-li.github.io#7]
看了这篇文章
操作了
但是有个疑问
我这个hexo 仓库是新创建的
用了你这方法
旧的文章的更新日期都是这个新仓库第一次commit的时间
用没有办法拿到文章真正的更新时间？

**Comment by wafer-li** [comment]
不好意思最近比较忙。

Travis CI 这篇文章比较老了，你可以从我的 travis ci 配置里面获取最新的修复更新时间的代码
